"""transforming schema

Revision ID: 5cfc72e753ba
Revises: 075b701a1a93
Create Date: 2025-05-27 16:16:34.166953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cfc72e753ba'
down_revision: Union[str, None] = '075b701a1a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('rules',
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission_name')
    )
    op.add_column('users', sa.Column('role_name', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_name'], ['name'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_name')
    op.drop_table('rules')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
